### PR TITLE
enhanced footer section done

### PR DESCRIPTION
**Pull request by NagasaiPraneeth**
**changes done:**

1. Redesigned New letter box for better usability and visual appeal.
2. Aligned and updated the icons for a more professional look, adding hover effects for improved interactivity.
3. Introduced animations for all elements to create a more dynamic user experience.
4. Changed the copyright heading to a more professional style.
5.it's responsive now

let me know any changes are there 
please assign me the level.
fixed:#97

changes made:
ss

### CODE REVIEW

**Comment by NagasaiPraneeth** [comment]
why my check got failed . did I do anything wrong ? i didn't understand why vercel check have failed as I am new to open source. can anyone help me?  @vanshchauhan21 @RachitSahu26

**Comment by vanshchauhan21** [comment]
> **changes done:**
> 
> 1. Redesigned New letter box for better usability and visual appeal.
> 2. Aligned and updated the icons for a more professional look, adding hover effects for improved interactivity.
> 3. Introduced animations for all elements to create a more dynamic user experience.
> 4. Changed the copyright heading to a more professional style.
>    5.it's responsive now
> 
> let me know any changes are there please assign me the level. fixed:#97
> 
> changes made: ss
Wow it's great 👍

**Comment by vanshchauhan21** [comment]
> why my check got failed . did I do anything wrong ? i didn't understand why vercel check have failed as I am new to open source. can anyone help me? @vanshchauhan21 @RachitSahu26

Screenshot_20241026-113509
You need to resolve this conflict issue

**Comment by RachitSahu26** [comment]
vansh this error will be solve first in your locally because yesterday i try everything to resolve it ,issue has in your locally project first ensure that your project is properly running as locally @vanshchauhan21

**Comment by RachitSahu26** [comment]
i think when you added chat bot functionality then this issue has reflexed

**Comment by vanshchauhan21** [comment]
> i think when you added chat bot functionality then this issue has reflexed

Yes implementation of chatbot affect the project

**Comment by vanshchauhan21** [comment]
> vansh this error will be solve first in your locally because yesterday i try everything to resolve it ,issue has in your locally project first ensure that your project is properly running as locally @vanshchauhan21

Ya sure I will do

**Comment by RachitSahu26** [comment]
> n of chatbot affect the project

just remove this functionality i will work on that when this will fix okay and first fix it locally and psuh it in main repo so that  i will sync it and again work it

**Comment by vanshchauhan21** [comment]
> > n of chatbot affect the project
> 
> just remove this functionality i will work on that when this will fix okay and first fix it locally and psuh it in main repo so that i will sync it and again work it

you can make another pull request for this i will assign you , actually i don't have my laptop right now i am on weekend , you can open another pull request for this i will assign you and then later merge

**Comment by RachitSahu26** [comment]
> > > n of chatbot affect the project
> > 
> > 
> > just remove this functionality i will work on that when this will fix okay and first fix it locally and psuh it in main repo so that i will sync it and again work it
> 
> you can make another pull request for this i will assign you , actually i don't have my laptop right now i am on weekend , you can open another pull request for this i will assign you and then later merge

yaa , but now i am working on another repo of the issue @vanshchauhan21 little bit wait please.. @vanshchauhan21

**Comment by vanshchauhan21** [comment]
> > > > n of chatbot affect the project
> > > 
> > > 
> > > just remove this functionality i will work on that when this will fix okay and first fix it locally and psuh it in main repo so that i will sync it and again work it
> > 
> > 
> > you can make another pull request for this i will assign you , actually i don't have my laptop right now i am on weekend , you can open another pull request for this i will assign you and then later merge
> 
> yaa , but now i am working on another repo of the issue @vanshchauhan21 little bit wait please.. @vanshchauhan21

Okay brother

**Comment by NagasaiPraneeth** [comment]
i sucessfully solved the conflicts . @vanshchauhan21 @RachitSahu26

**Review by vanshchauhan21 — APPROVED** [review]

**Pull request merged**
