### PR TITLE
Corrected logo shadow in footer

### LINKED ISSUE #248: 🐛: Misalignment of logo shadow on footer
### Title

Fix Misalignment of Logo Shadow in Footer

### Bug

Misalignment of Logo Shadow in Footer

### Changes

Corrected the alignment of the logo shadow in the footer to ensure consistent appearance and positioning.
Updated CSS styling for the logo shadow to improve visual coherence and aesthetics across all screen sizes.

### Screenshots 📷

image

### Full Name

Priyanshi Bhargava

### Participant Role

GSSoC-ext :Contributor

### PR DESCRIPTION
**Pull request by Priyanshi0112**
fixed #248 
This PR addresses the shadow styling of the logo in the footer to enhance visual consistency and clarity across themes

image

### CODE REVIEW

**Comment by Hemu21** [comment]
@MastanSayyad

**Comment by MastanSayyad** [comment]
@vanshchauhan21 remove all labels!

**Comment by MastanSayyad** [comment]
@vanshchauhan21 i didn't get response from you yet, kindly respond @Priyanshi0112 kindly explain yourself otherwise we need to take strict actions. I already gave warning to both of for greater good of the program and you guys pls do the needful. 

If not done till 11:00 AM, we need to discard both of you from PA position and Contributor position

**Comment by Priyanshi0112** [comment]
> @vanshchauhan21 i didn't get response from you yet, kindly respond @Priyanshi0112 kindly explain yourself otherwise we need to take strict actions. I already gave warning to both of for greater good of the program and you guys pls do the needful.
> 
> If not done till 11:00 AM, we need to discard both of you from PA position and Contributor position

@MastanSayyad  I already have sent u the mail

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 i didn't get response from you yet, kindly respond @Priyanshi0112 kindly explain yourself otherwise we need to take strict actions. I already gave warning to both of for greater good of the program and you guys pls do the needful.
> 
> If not done till 11:00 AM, we need to discard both of you from PA position and Contributor position

Sorry sir kal me function me tha isliye reply nhi kar paya

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 i didn't get response from you yet, kindly respond @Priyanshi0112 kindly explain yourself otherwise we need to take strict actions. I already gave warning to both of for greater good of the program and you guys pls do the needful.
> 
> If not done till 11:00 AM, we need to discard both of you from PA position and Contributor position

Abhi remove krta hu labels

**Comment by Priyanshi0112** [comment]
@MastanSayyad 

Why are only my levels being removed? Please remove everyone else's levels as well. On the last day, Vansh gave everyone Level 3, so I request that all other levels be removed too.

image
image

**Comment by Priyanshi0112** [comment]
@MastanSayyad 

Please clarify why only my levels are being removed. Is it because I am in the top 10?

**Comment by MastanSayyad** [comment]
@Priyanshi0112 It is because your contributions have high labels for minor changes, you have 100+ PRs open here and each one is labeled wrong, I gave you the reasons in your each PR

and No you are not the only one whose points are reducing

image

**Comment by Priyanshi0112** [comment]
> > @Priyanshi0112 It is because your contributions have high labels for minor changes, you have 100+ PRs open here and each one is labeled wrong, I gave you the reasons in your each PR
> > and No you are not the only one whose points are reducing
> > image
> 
> This isn’t a valid point. Please check his pr @RachitSahu26 he also completed over 100 PRs, so was there any decrement applied to his work? If so, why? All this should have been checked before updating the leaderboard. Why did this issue come up after declaring the final results? If this isn't a scam, then what is? Fine, reduce the level if necessary, but why were the old contributions removed?

**Comment by MastanSayyad** [comment]
> This isn’t a valid point.

This is a valid point, @Priyanshi0112. Have you even read the GSSoC guidelines before contributing? It seems you might be new to open source.

Please refer to this for clarification and your valid points: https://github.com/orgs/GSSoC24/discussions/1085

>  Please check this carefully @RachitSahu26 completed over 100 PRs, so was there any decrement applied to their work? If so, why?

I reviewed the PRs, and I didn't find minor changes with level 3 labels in their contributions. Rachit has a balanced score distribution with only 75 PRs in this repo across level 1, level 2, and level 3 labels, unlike yours, where minimal adjustments were labeled with level 3.

> All this should have been checked before updating the leaderboard. Why did this issue come up after declaring the final results? If this isn't a scam, then what is?

Regarding this, As for the timing of this issue, final reviews are conducted to ensure fairness among top contributors before announcing the results, you jumped to the leaderboard out of no where + You are not the only one whose points were reduced.

Finally, there is a difference between spam and scam. *Spam* refers to excessive activity (which is yours), while *scam* implies cheating.

Thank you!

**Pull request merged**
