### PR TITLE
Adjust toggle, table for dark theme

### LINKED ISSUE #19: Feature: highlighted Background for price type chosen
Currently, the price type chosen is not clear, as it doesn't highlight the chosen one
image

Instead, it will be rather helpful and clear if it is
image

to detect the active type chosen

Also the dropdown in dark mode can be enhanced
from
image

to dropdown with dark mode

I am a GSSOC-ext contributor. I would like to take on this issue. Thank you!

### PR DESCRIPTION
**Pull request by nidhi2026**
Adjusted dark theme for better visibility and experience in dark mode
fixes #19 
here is a demo after the changes:

https://github.com/user-attachments/assets/738019a6-9eb8-45b0-84a3-919c1af415a9

### CODE REVIEW

**Comment by nidhi2026** [comment]
@vanshchauhan21 I have raised the pr. Is it fine, or should I make some changes

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 I have raised the pr. Is it fine, or should I make some changes

Yes sure you can make

**Comment by nidhi2026** [comment]
@vanshchauhan21 thank you for merging 
The label is Gssoc-ext like the gssoc extended

**Comment by nidhi2026** [comment]
@vanshchauhan21 , sorry to bother again, but I am not a contributor of gssoc but of gssoc extended,
So a humble request to add "gssoc-ext" label as in the image above

**Comment by vanshchauhan21** [comment]
Okay done ✅

**Pull request merged**
