### PR TITLE
added send email functionality

### PR DESCRIPTION
**Pull request by AyushSharma72**
issue number #379

added send email functionality upon form submission by the user 

images:
Screenshot (78)

send message:
Screenshot (80)

email:
Screenshot (81)

please review this pr @vanshchauhan21

### CODE REVIEW

**Comment by vanshchauhan21** [comment]
> issue number #379
> 
> added send email functionality upon form submission by the user
> 
> images: Screenshot (78)
> 
> send message: Screenshot (80)
> 
> email: Screenshot (81)
> 
> please review this pr @vanshchauhan21

Bhai isme mail meri dalni ha ?

**Comment by AyushSharma72** [comment]
> > issue number #379
> > added send email functionality upon form submission by the user
> > images: Screenshot (78)
> > send message: Screenshot (80)
> > email: Screenshot (81)
> > please review this pr @vanshchauhan21
> 
> Bhai isme mail meri dalni ha ?

Yes add your email you will receive it on your mail then

**Comment by vanshchauhan21** [comment]
> > issue number #379
> > added send email functionality upon form submission by the user
> > images: Screenshot (78)
> > send message: Screenshot (80)
> > email: Screenshot (81)
> > please review this pr @vanshchauhan21
> 
> Bhai isme mail meri dalni ha ?

chauhanvansh313@gmail.com 
Yer bhai add krdo

**Comment by AyushSharma72** [comment]
> > > issue number #379
> > > added send email functionality upon form submission by the user
> > > images: Screenshot (78)
> > > send message: Screenshot (80)
> > > email: Screenshot (81)
> > > please review this pr @vanshchauhan21
> > 
> > 
> > Bhai isme mail meri dalni ha ?
> 
> [chauhanvansh313@gmail.com](mailto:chauhanvansh313@gmail.com) Yer bhai add krdo

ok

**Comment by AyushSharma72** [comment]
> > > issue number #379
> > > added send email functionality upon form submission by the user
> > > images: Screenshot (78)
> > > send message: Screenshot (80)
> > > email: Screenshot (81)
> > > please review this pr @vanshchauhan21
> > 
> > 
> > Bhai isme mail meri dalni ha ?
> 
> [chauhanvansh313@gmail.com](mailto:chauhanvansh313@gmail.com) Yer bhai add krdo

ok

**Pull request merged**
