### PR TITLE
🚀 Automate Connections with GitHub Actions!

### LINKED ISSUE #124: 🚀 Automate Connections with GitHub Actions!
We can implement github workflows for the following things:

Auto comment on issue Closed and Opened
Auto comment on PR mergs
Auto comment on PR raises
Using this workflows makes you'r repo more interactive !

please assign me and i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label
@vanshchauhan21

### PR DESCRIPTION
**Pull request by amiya-cyber**
implemented github workflows for the following things:

Auto comment on issue Closed and Opened
Auto comment on PR mergs
Auto comment on PR raises
Using this workflows makes you'r repo more interactive !

fixes #124 
close #124 

add level2 or level 3 label

### CODE REVIEW

**Comment by vanshchauhan21** [comment]
> implemented github workflows for the following things:
> 
> Auto comment on issue Closed and Opened Auto comment on PR mergs Auto comment on PR raises Using this workflows makes you'r repo more interactive !
> 
> fixes #124 close #124
> 
> add level2 or level 3 label

Done bro 👍

**Comment by amiya-cyber** [comment]
Thank you so much @vanshchauhan21 it means a lot

**Comment by vanshchauhan21** [comment]
> Thank you so much @vanshchauhan21 it means a lot

🫂

**Review by MastanSayyad — COMMENTED** [review]
Add level 1 @vanshchauhan21 

image

**Comment by vanshchauhan21** [comment]
> Add level 1 @vanshchauhan21
> 
> image

Oky

**Comment by amiya-cyber** [comment]
hello @MastanSayyad i think i have done atleast 3 workflows added 3 new files in a single pr so i think you can give atleast level 2 label or level 3

**Pull request merged**
