### PR TITLE
add header in the FAQ page

### PR DESCRIPTION
**Pull request by RachitSahu26**
Fixed: #102

just merge it and again  i am going to make another feature @vanshchauhan21

### CODE REVIEW

**Comment by RachitSahu26** [comment]
https://github.com/user-attachments/assets/c593494a-e005-47d4-a0ba-ff1b73117b57

**Comment by vanshchauhan21** [comment]
> notification.mp4

There are some errors?

**Comment by RachitSahu26** [comment]
> > notification.mp4
> 
> There are some errors?

okay but could you please share screen shot of it @vanshchauhan21

**Comment by RachitSahu26** [comment]
how can i see , what is the error @vanshchauhan21

**Comment by vanshchauhan21** [comment]
> how can i see , what is the error @vanshchauhan21
Fixed and merged.

**Comment by vanshchauhan21** [comment]
@RachitSahu26 bro android view me footer section bhot bada dkhra ha use resolve kr skta ha ?

**Comment by vanshchauhan21** [comment]
> @RachitSahu26 bro android view me footer section bhot bada dkhra ha use resolve kr skta ha ?

**Comment by RachitSahu26** [comment]
> @RachitSahu26 bro android view me footer section bhot bada dkhra ha use resolve kr skta ha ?

okay Vansh bro but again i gonna create some issues and then one by one i will resolve it okay basically what i mean to say that whatever  issue i will resolve i will create new issue then i will fix it or please  add good labels becasue my  rank is 162 of the GSSoC now  i want to grab rank between 50

**Comment by vanshchauhan21** [comment]
> > @RachitSahu26 bro android view me footer section bhot bada dkhra ha use resolve kr skta ha ?
> 
> okay Vansh bro but again i gonna create some issues and then one by one i will resolve it okay basically what i mean to say that whatever issue i will resolve i will create new issue then i will fix it or please add good labels becasue my rank is 162 of the GSSoC now i want to grab rank between 50

Sure  bro you are doing great job 👍

**Comment by RachitSahu26** [comment]
@vanshchauhan21  now i am working on multi language support feature okay go of this issue and add some labels

**Comment by vanshchauhan21** [comment]
> > @RachitSahu26 bro android view me footer section bhot bada dkhra ha use resolve kr skta ha ?
> 
> okay Vansh bro but again i gonna create some issues and then one by one i will resolve it okay basically what i mean to say that whatever issue i will resolve i will create new issue then i will fix it or please add good labels becasue my rank is 162 of the GSSoC now i want to grab rank between 50

I added level 3 labels in you all issues 👍

**Pull request merged**
