### PR TITLE
fixed broken theme in dark mode

### LINKED ISSUE #179: BUG : Landing page issue in dark mode
The landing page is not properly behaving in dark mode. The navbar changes color but the page doesn't.

image

Please assign it under WoB, GSSoC and Hacktoberfest

### PR DESCRIPTION
**Pull request by Irtesaam**
Realted issue : 
Fixed #179 

Description : 
Fixed broken theme in dark mode. Only navbar was changing according to the theme. Now the page's body also changes.

Screenshots : 
Before : 
image

After : 
image

### CODE REVIEW

**Comment by vanshchauhan21** [comment]
> Realted issue : Fixes : #179
> 
> Description : Fixed broken theme in dark mode. Only navbar was changing according to the theme. Now the page's body also changes.
> 
> Screenshots : Before : image
> 
> After : image

Your deployment was failed

**Comment by Irtesaam** [comment]
@vanshchauhan21 Why so ?

**Comment by Irtesaam** [comment]
What's this commit for ?

image

I guess there was no problem in deplyment before this commit as evident in the screenshot. What could be the issue ?

image

**Comment by vanshchauhan21** [comment]
> What's this commit for ?
> 
> image
> 
> I guess there was no problem in deplyment before this commit as evident in the screenshot. What could be the issue ?
> 
> image

Screenshot_20241029-184029
See this there is syntax error

**Comment by Irtesaam** [comment]
The syntax error was in the line 461. I have fixed it. Try redeployment.

image

**Comment by Irtesaam** [comment]
@vanshchauhan21 Please add labels to this PR.

**Pull request merged**
