### PR TITLE
Add Licensing Page | Issue #513

### LINKED ISSUE #513: [Feature Request]: Creation and Addition of Licensing Page in Footer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To provide clarity and transparency regarding the use of software and resources on the CryptoTracker platform, I propose the addition of a dedicated Licensing Page. This page will outline the licensing terms and conditions applicable to our platform, helping users understand their rights and responsibilities.

## Objectives
1. **Clarify Licensing Terms**: Clearly articulate the types of licenses under which the software and resources are provided, such as open-source licenses, commercial licenses, etc.
2. **Inform Users**: Provide users with essential information about how they can use, modify, and distribute the software and content within legal parameters.
3. **Enhance Transparency**: Build trust with users by being upfront about licensing agreements and restrictions.

### Benefits

Implementing a Licensing Page will empower users with the knowledge they need to utilize the CryptoTracker platform effectively and legally. It will also enhance our commitment to transparency and user education.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Shariq2003**
#### Issue Title
**Licensing Page Addition for CryptoTracker Platform**  
*This PR adds a dedicated Licensing Page to outline licensing terms and conditions for CryptoTracker platform users.*

fix #513 

- [x] I have provided the issue title.

---

#### Info about the Related Issue
**What's the goal of the project?**  
The goal of this project is to provide transparency regarding the use of software and resources on the CryptoTracker platform, helping users understand their rights and responsibilities in relation to licensing.

image
image

- [x] I have described the aim of the project.

---

#### Name
**Please mention your name.**  
Shariq

- [x] I have provided my name.

---

#### GitHub ID
**Please mention your GitHub ID.**  
shariq2003

- [x] I have provided my GitHub ID.

---

#### Identify Yourself
**Mention in which program you are contributing (e.g., WoB, GSSOC, SSOC, Hactoberfest).**  
GSSOC-ext

- [x] I have mentioned my participant role.

---

#### Closes
**Enter the issue number that will be closed through this PR.**  
Closes: #513 

- [x] I have provided the issue number.

---

#### Describe the Add-ons or Changes You've Made
**Give a clear description of what you have added or modified.**  
- Created a **Licensing Page** to articulate the licensing terms for CryptoTracker users.
- Added content on the types of licenses (open-source, commercial, etc.) under which the platform and its resources are provided.
- Styled the page similar to the Privacy Policy page for consistency across the platform.
- Ensured the page is responsive for mobile users.

- [x] I have described my changes.

---

#### Type of Change
**Select the type of change:**  
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

- [x] I have selected the type of change.

---

#### How Has This Been Tested?
**Describe how your changes have been tested.**  
- The **Licensing Page** was tested across multiple screen sizes to ensure proper display on desktop and mobile devices.
- Verified that all links and sections display correctly.
- Cross-checked with Privacy Policy page to ensure consistent styling.

- [x] I have described my testing process.

---

#### Checklist
**Please confirm the following:**  
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Shariq2003** [comment]
@vanshchauhan21 sir review and merge

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 sir review and merge

hey my vercel deployement limit exceed that's why  i am anable to merge wait for an hours i will do something

**Comment by Shariq2003** [comment]
> > @vanshchauhan21 sir review and merge
> 
> hey my vercel deployement limit exceed that's why i am anable to merge wait for an hours i will do something

I can send you the UI

**Comment by Shariq2003** [comment]
> > @vanshchauhan21 sir review and merge
> 
> hey my vercel deployement limit exceed that's why i am anable to merge wait for an hours i will do something

Hey @vanshchauhan21 someone ruined the app.js and footer.jsx files while merging conflicts that cause the whole app down, in the main branch currently.

**Comment by Shariq2003** [comment]
I have fixed that in my local, and also going to push along with this PR, if you agree.

**Comment by Shariq2003** [comment]
@vanshchauhan21 sir

**Comment by Shariq2003** [comment]
Please.............

**Comment by Shariq2003** [comment]
@vanshchauhan21 sir

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 sir

Wait bro deployment limit khtm hgyi ha vercel ki

**Comment by Shariq2003** [comment]
> > @vanshchauhan21 sir
> 
> Wait bro deployment limit khtm hgyi ha vercel ki

bro 7pm pr to GSSOC hi khatm hijayeva

**Comment by vanshchauhan21** [comment]
> > > @vanshchauhan21 sir
> > 
> > 
> > Wait bro deployment limit khtm hgyi ha vercel ki
> 
> @vanshchauhan21 bro 7pm pr to GSSOC hi khatm hijayeva and i have provided the working UI demo above, also if you want i can also share my screen via gmeet

Merged bro

**Pull request merged**
