### PR TITLE
Created pr-checker.yml

### LINKED ISSUE #127: Pull Request Issue checker workflow🚀
Description: We need to create a GitHub Actions workflow that automates the validation of pull requests (PRs). This workflow will ensure that all PRs meet the following criteria before being merged:

PR Description Check: Every PR must have a description. If the description is missing, the PR should fail the check.

Acceptance Criteria:

A GitHub Action workflow is triggered on PR events (opened, edited).

The workflow checks the PR body for:

A non-empty description.
The presence of Fixes # or Fixes #NEW.
If the criteria are not met:

The workflow should fail and return clear error messages.
If the checks pass:

A confirmation message is outputted.

please @vanshchauhan21 assign this with level 3 label

### PR DESCRIPTION
**Pull request by amiya-cyber**
Description:
This workflow automatically runs checks on every pull request. It ensures that PRs meet basic criteria, such as:

issue #127 
close #127 

1. Checking for a descriptive title and body.
2. Running linting and basic tests to validate code quality.
3. This helps maintain PR quality and catch issues early in the review process.

### CODE REVIEW

**Comment by amiya-cyber** [comment]
hey buddy @vanshchauhan21 thanks a lot

**Comment by vanshchauhan21** [comment]
> hey buddy @vanshchauhan21 thanks a lot

🫂👍

**Review by MastanSayyad — COMMENTED** [review]
Remove the levels for this PR @vanshchauhan21 as already 2 PRs have levels in this Repo

**Comment by vanshchauhan21** [comment]
> Remove the levels for this PR @vanshchauhan21 as already 2 PRs have levels in this Repo

Oky oky

**Pull request merged**
