### PR TITLE
Updated README with project details

### PR DESCRIPTION
**Pull request by Ishratnoori**
Dear @vanshchauhan21,

I have completed the contributing guide as previously discussed. Please find the key enhancements made to the project documentation:

1.Enhanced Project Description.
2.Listed the application features for easy reference.
3.Specified the technologies used in the project.
4.Added step-by-step installation guidance for new users.
5.Clear steps for Contributing Section.
6.Added a light-hearted ending to engage readers.

Please merge these changes into the main branch.
I’d also appreciate being assigned to GSSOC-Ext and Hacktoberfest.

Thank you!

Best regards,
Ishrat noori :)

### CODE REVIEW

**Comment by Ishratnoori** [comment]
Kindly merge this request and label me as hacktoberfest-accepted and gssoc :)

**Comment by Ishratnoori** [comment]
Subject: Request for Verification of PR Contribution to GSSoC Leaderboard

Hi @vanshchauhan21 Vansh,

I hope you’re doing well. I recently submitted a pull request [#36](https://github.com/vanshchauhan21/CryptoTracker/pull/36) for the CryptoTracker project, which was merged 2 days ago. However, my contribution doesn’t seem to be reflected on the GSSoC leaderboard yet.

Could you kindly check if everything is in order from your side regarding the PR tagging or any submission steps that might impact the leaderboard? I’d appreciate any help you could provide to ensure my contribution gets recorded properly.

Thanks a lot for your time and support!

Best regards,
Ishrat noori :)

**Comment by vanshchauhan21** [comment]
> Subject: Request for Verification of PR Contribution to GSSoC Leaderboard
> 
> Hi @vanshchauhan21 Vansh,
> 
> I hope you’re doing well. I recently submitted a pull request [#36](https://github.com/vanshchauhan21/CryptoTracker/pull/36) for the CryptoTracker project, which was merged 2 days ago. However, my contribution doesn’t seem to be reflected on the GSSoC leaderboard yet.
> 
> Could you kindly check if everything is in order from your side regarding the PR tagging or any submission steps that might impact the leaderboard? I’d appreciate any help you could provide to ensure my contribution gets recorded properly.
> 
> Thanks a lot for your time and support!
> 
> Best regards, Ishrat noori :)

Yes every thing is in correct order , wait your contribution seem soon .

**Comment by Ishratnoori** [comment]
Screenshot 2024-10-24 163521
:(

**Comment by vanshchauhan21** [comment]
> image
> 
> Hi @vanshchauhan21 Vansh,
> 
> Thanks for getting back to me! I noticed that my pull request for the CryptoTracker project ([PR #36](https://github.com/vanshchauhan21/CryptoTracker/pull/36)) was merged, but it doesn't seem to show up on the GSSoC leaderboard like my previous contribution for FusionFlow.
> 
> I understand that there might be something missing or different in the process for this PR. Could you please check if there's any specific tagging or step required for it to reflect properly? I'd really appreciate your help with this.
> 
> Thanks again for ur time!
> 
> Ishrat noori :)

Wait list will update soon, I checked all the tagging every thing is correct

**Comment by vanshchauhan21** [comment]
Screenshot_20241024-175447
See all the tags are in order and correct, wait a little list will update soon 🙂

**Comment by Ishratnoori** [comment]
Hi @vanshchauhan21,

Thank you for your support! I'm excited to see that my pull request for the CryptoTracker project is now reflected on the GSSoC leaderboard. I appreciate your help in ensuring everything was in order.

Best regards,
Ishrat noori :)

**Comment by vanshchauhan21** [comment]
> Hi @vanshchauhan21,
> 
> Thank you for your support! I'm excited to see that my pull request for the CryptoTracker project is now reflected on the GSSoC leaderboard. I appreciate your help in ensuring everything was in order.
> 
> Best regards, Ishrat noori :)

Welcome @Ishratnoori you did a brilliant job in this project 💐

**Pull request merged**
