### PR TITLE
added chatbot for enhanced user experience

### LINKED ISSUE #72: [FEATURE] Integrate a Chatbot for Instant User Support
Enhance the website's user experience by integrating a chatbot that provides instant answers to user inquiries. The chatbot should be easily accessible, provide relevant responses, and offer seamless assistance for common queries, improving user engagement and support.

Add a chatbot icon or button that floats on the bottom-right corner of the site.
When clicked, the chatbot window should expand with a smooth animation, displaying an input field and previous chat history.

The chatbot should respond to frequently asked questions (related to the FAQ section) and common inquiries about products or services.
Implement a fallback response for questions outside the chatbot's scope (e.g., "Sorry, I don't have an answer for that. Please contact our support team.").

please assign this to me under gssoc-ext and hacktoberfest

### PR DESCRIPTION
**Pull request by sezallagwal**
Integrated a chatbot that provides instant answers to user inquiries. The chatbot is site specific and answers queries related to the website or general queries
closes #72 

https://github.com/user-attachments/assets/688a2934-7cba-454c-ae9a-4b079e3d34ec

### CODE REVIEW

**Comment by vanshchauhan21** [comment]
@sezallagwal hey only chatbot are showing in project? You did something wrong? Please look into the matter immediately

**Comment by sezallagwal** [comment]
@vanshchauhan21 no its not because of chatbot, its because environment variable for the publishable key is either missing, incorrectly configured in the production environment
image
you can take a look at console

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 no its not because of chatbot, its because environment variable for the publishable key is either missing, incorrectly configured in the production environment image you can take a look at console

Can you resolve this issue? As soon as possible

**Comment by sezallagwal** [comment]
It seems to be an issue with the environment variable configuration for the production deployment. As a contributor, I don’t have access to the production environment settings or Vercel dashboard, so I can’t directly resolve this issue. I can only test the application in development mode locally. 
To fix this you need to go to your Vercel project, navigate to "Settings" > "Environment Variables," and verify that the REACT_APP_CLERK_PUBLISHABLE_KEY is there.
After updating the environment variables, redeploy your application to ensure changes take effect.

Let me know if you need any further help from my end! @vanshchauhan21

**Pull request merged**
