### PR TITLE
added Learn Section

### LINKED ISSUE #108: Feature Request: "Learn" Section for Educational Resources
## Overview
Add a "Learn" section to the CryptoTracker website, where users can access educational content related to cryptocurrency trading, blockchain fundamentals, and market analysis. This feature aims to help users build their knowledge and make informed investment decisions.

## Purpose
To enhance user experience by providing a comprehensive learning hub within the CryptoTracker platform. This section will help beginners understand cryptocurrency better and provide advanced resources for experienced traders.

## Proposed Content for the "Learn" Section
1. **Crypto Trading Basics**
2. **Blockchain Fundamentals**
3. **Market Analysis Techniques**

please assign this to me under `gssoc-ext` and `hacktoberfest` @vanshchauhan21

### PR DESCRIPTION
**Pull request by sezallagwal**
fixes #108 
@vanshchauhan21 please review this pr thanks!

### CODE REVIEW

**Comment by sezallagwal** [comment]
@vanshchauhan21 Can you add level3 label

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 Can you add level3 label

Sorry' as per the guidelines I can't

**Comment by sezallagwal** [comment]
> > @vanshchauhan21 Can you add level3 label
> 
> Sorry' as per the guidelines I can't

you forgot to add labels in https://github.com/vanshchauhan21/CryptoTracker/pull/191

**Comment by amitb0ra** [comment]
but its a new page right? like #117

**Pull request merged**
